[package]
name = "typstify"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
color-eyre = "0.6"
poise = "0.7.0"
tokio = "1.53.1"
typst = "0.15.1"
typst-as-lib = "0.16.0"
typst-assets = { version = "0.15.1", features = ["fonts"] }
typst-layout = "0.15.1"
typst-pdf = "0.15.1"
typst-render = "0.15.1"
typst-svg = "0.15.1"
