name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  cargo-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Cargo binary
      run: cargo build --release

  docker-build:
    needs: cargo-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag typstify:1.0.0

  docker-login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}

  docker-push:
    needs: [docker-build, docker-login]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Push to Docker Hub
      run: docker push jockehertz/typstify:latest
